services:
  energia-service:
    image: guilhermejr/sistema-energia-service
    container_name: energia-service
    restart: always
    ports:
      - "9001:9001"

networks:
  default:
    external: true
    name: rede