CREATE TABLE public.geracao (
    data DATE NOT NULL,
    gerado NUMERIC(5,1) NOT NULL,
    criado TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    atualizado TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT geracao_pkey PRIMARY KEY (data)
);